### ISSUE TITLE
README doesn't mention loading the plugin

### ISSUE THREAD

**Issue by mpounsett** [pelican-plugins/series#29]
The installation instructions in the README don't mention loading the plugin.

**Comment by justinmayer** [comment]
As noted in [my comment in the corresponding PR](https://github.com/pelican-plugins/series/pull/30#issuecomment-1703765860), the installation instructions don't mention enabling the plugin because by default the plugin will be automatically detected, registered, and enabled without any action by the end user — **_provided that_** the `PLUGINS` setting has not been explicitly defined by the end user.

In line with language I have added to other plugin READMEs, via 2d6cf2d I have added a paragraph to this plugin's README to make that fact more visible, along with a link to the relevant documentation that clearly explains this behavior.
